# rustfmt configuration for mail_parser_rust
# Enforces consistent Rust formatting
# Note: Some advanced features require nightly Rust

# Edition
edition = "2021"

# Line width
max_width = 100

# Formatting style
newline_style = "Unix"
hard_tabs = false
tab_spaces = 4

# Function formatting
fn_params_layout = "Tall"
fn_call_width = 80

# Misc formatting
use_small_heuristics = "Default"
use_field_init_shorthand = true
force_explicit_abi = true

# Chain formatting
chain_width = 60
short_array_element_width_threshold = 10

# Where clauses
match_block_trailing_comma = true

# Struct formatting
struct_variant_width = 35

# Unstable features (require nightly Rust)
# Uncomment if using nightly:
# unstable_features = true
# indent_style = "Block"
# wrap_comments = true
# comment_width = 80
# imports_granularity = "Crate"
# group_imports = "StdExternalCrate"
# brace_style = "SameLineWhere"
# control_brace_style = "AlwaysSameLine"
# normalize_comments = true
# normalize_doc_attributes = true
# format_code_in_doc_comments = true
# format_strings = true
# format_macro_matchers = true
# format_macro_bodies = true
# trailing_comma = "Vertical"
# trailing_semicolon = true
# fn_single_line = false
# where_single_line = false
# blank_lines_upper_bound = 1
# blank_lines_lower_bound = 0
# struct_lit_single_line = true
